[package]
name = "zcore"
version = "0.1.0"
authors = ["PanQL <panqinglin00@163.com>", "Yuekai Jia <equation618@gmail.com>"]
edition = "2018"
default-run = "zcore"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
# Disable cargo test, bench and doc for this package
name = "zcore"
test = false
bench = false
doc = false

[features]
default = ["libos"]
colorless-log = []
graphic = ["kernel-hal/graphic"]
link-user-img = []

zircon = ["zcore-loader/zircon"]
linux = ["zcore-loader/linux", "linux-object", "rcore-fs", "rcore-fs-sfs"]

libos = ["kernel-hal/libos", "zcore-loader/libos", "async-std", "chrono", "rcore-fs-hostfs"]
board-qemu = []
board-d1 = ["link-user-img"]

[dependencies]
log = "0.4"
spin = "0.9"
cfg-if = "1.0"
lazy_static = { version = "1.4", features = ["spin_no_std" ] }
bitmap-allocator = { git = "https://github.com/rcore-os/bitmap-allocator", rev = "b3f9f51" }
trapframe = "0.8.0"
kernel-hal = { path = "../kernel-hal", default-features = false, features = ["smp"] }
zcore-loader = { path = "../loader", default-features = false }
zircon-object = { path = "../zircon-object" }
linux-object = { path = "../linux-object", optional = true }
# rcore-fs-sfs = { git = "https://github.com/rcore-os/rcore-fs", rev = "7c232ec", optional = true }
# rcore-fs = { git = "https://github.com/rcore-os/rcore-fs", rev = "7c232ec", optional = true }
rcore-fs-sfs = { git = "https://github.com/DeathWish5/rcore-fs", branch = "async-fs", optional = true }
rcore-fs = { git = "https://github.com/DeathWish5/rcore-fs", branch = "async-fs", optional = true }
virtio-drivers = { git = "https://github.com/DeathWish5/async-virtio-drivers", optional = true }
async-trait = "0.1"
# FIX LATER
# rvm = { git = "https://github.com/rcore-os/RVM", rev = "382fc60", optional = true }
riscv = { version = "0.7", features = ["inline-asm"] }
# const_env_impl = "0.1.3"


# LibOS mode
[target.'cfg(not(target_os = "none"))'.dependencies]
async-std = { version = "1.10", optional = true }
chrono = { version = "0.4", optional = true }
rcore-fs-hostfs = { git = "https://github.com/rcore-os/rcore-fs", rev = "7c232ec", optional = true }

# Bare-metal mode
[target.'cfg(target_os = "none")'.dependencies]
buddy_system_allocator = "0.7"
# executor = { git = "https://github.com/rcore-os/executor.git", rev = "04b6b7b" }
executor = { git = "https://github.com/DeathWish5/executor.git" }

[target.'cfg(target_arch = "riscv64")'.dependencies]
rlibc = "1.0"

# Bare-metal mode on x86_64
[target.'cfg(all(target_os = "none", target_arch = "x86_64"))'.dependencies]
rboot = { git = "https://github.com/rcore-os/rboot.git", rev = "39d6e24", default-features = false }
<<<<<<< HEAD
# rvm = { git = "https://github.com/rcore-os/RVM", rev = "e91d625", optional = true }

# [patch.'https://github.com/DeathWish5/async-virtio-drivers']
# virtio-drivers = { path = "../../ASYNC/virtio-drivers" }

# [patch.'https://github.com/DeathWish5/rcore-fs']
# rcore-fs = { path = "../../../ASYNC/rcore-fs/rcore-fs" }
# rcore-fs-sfs = { path = "../../../ASYNC/rcore-fs/rcore-fs-sfs" }
# rcore-fs-ramfs = { path = "../../../ASYNC/rcore-fs/rcore-fs-ramfs" }
# rcore-fs-mountfs = { path = "../../../ASYNC/rcore-fs/rcore-fs-mountfs" }
# rcore-fs-devfs = { path = "../../../ASYNC/rcore-fs/rcore-fs-devfs" }

# [patch.'https://github.com/DeathWish5/executor.git']
# executor = { path = "../../ASYNC/executor/executor" }
=======
# rvm = { git = "https://github.com/rcore-os/RVM", rev = "e91d625", optional = true }
>>>>>>> riscv_muticore
